export const techStackIcons: Record<string, string> = {
  NextJS: '/static/icons/nextjs.svg',
  React: '/static/icons/react.svg',
  'React Native': '/static/icons/react.svg',
  TypeScript: '/static/icons/typescript.svg',
  'Tailwind CSS': '/static/icons/tailwindcss.svg',
  Flutter: '/static/icons/flutter.svg',
  Dart: '/static/icons/dart.svg',
  Pocketbase: '/static/icons/pocketbase.png',
  Laravel: '/static/icons/laravel.svg',
  FastAPI: '/static/icons/fastapi.svg',
  Firebase: '/static/icons/firebase.svg',
  Docker: '/static/icons/docker.svg',
  Git: '/static/icons/git.svg',
  PostgreSQL: '/static/icons/postgresql.svg',
  MongoDB: '/static/icons/mongodb.svg',
  NodeJS: '/static/icons/nodejs.svg',
}
